[pytest]
##命令行参数，用空格分隔
addopts = -vs --alluredir=./temps --clean-alluredir
# 冒烟测试用例执行方式
;addopts = -vs -m smoke
#测试用例文件夹.
testpaths = ./testcases
#测试搜索的模块文件名称
python_files = test_*.py
#测试搜索的测试类名称
python_classes = Test*
#测试搜索的测试函数名
python_functions = test_*
#标记只执行特定的用例mark
markers =
    smoke:冒烟测试

log_file = logs/pytest.log
log_file_level = DEBUG
log_file_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S